// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using bob_api.Data;

#nullable disable

namespace bob_api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240321095219_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("bob_api.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c468a87b-5cbc-4d7a-bce1-ac38424a6b1b"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(357),
                            Name = "Girl",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(357)
                        },
                        new
                        {
                            Id = new Guid("082c44a8-5d8c-4b7d-b4aa-ef31cc202338"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(320),
                            Name = "Boy",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(323)
                        },
                        new
                        {
                            Id = new Guid("79ffc79c-1203-45d7-a60d-522116a07589"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(359),
                            Name = "BTS",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(359)
                        },
                        new
                        {
                            Id = new Guid("8d7b666b-d420-49fc-921e-507fb60f0c56"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(360),
                            Name = "StrayKids",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(361)
                        },
                        new
                        {
                            Id = new Guid("c0a87bf6-0057-48c8-a0a3-5a1548e7e827"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(362),
                            Name = "BigBang",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(362)
                        },
                        new
                        {
                            Id = new Guid("651ec71d-6595-4da6-9208-9ee50c3db5d3"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(363),
                            Name = "Ateez",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(363)
                        },
                        new
                        {
                            Id = new Guid("35db38c3-8949-4c43-bf66-2379c5f40d12"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(364),
                            Name = "Blackpink",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(365)
                        },
                        new
                        {
                            Id = new Guid("71b337d1-044b-4e1d-a006-c1ac44b390fd"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(366),
                            Name = "Red Velvet",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(366)
                        },
                        new
                        {
                            Id = new Guid("fb06df6e-5c03-40a0-a393-36046864dd38"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(367),
                            Name = "LE SSERAFIM.",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(367)
                        },
                        new
                        {
                            Id = new Guid("c2999434-3a40-4773-9874-3480b407b468"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(370),
                            Name = "(G)I-DLE.",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(370)
                        },
                        new
                        {
                            Id = new Guid("783a12af-a925-456a-82b1-8a6d999998dc"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(371),
                            Name = "Girls Generation",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(371)
                        },
                        new
                        {
                            Id = new Guid("f4ccb7fe-4090-4e30-8ade-1a3be7c8c266"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(372),
                            Name = "EXO",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(372)
                        },
                        new
                        {
                            Id = new Guid("7fc4d300-3c0a-4a94-ac2d-2c1572270799"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(374),
                            Name = "Seventeen",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(375)
                        },
                        new
                        {
                            Id = new Guid("b064dda5-3ae4-43f4-a265-604ee6b8bda6"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(373),
                            Name = "Twice",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(373)
                        },
                        new
                        {
                            Id = new Guid("cb2b831f-9fd1-43d8-867b-f03067414658"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(375),
                            Name = "LightStick",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(376)
                        },
                        new
                        {
                            Id = new Guid("713af980-25c7-4527-b563-d20941644593"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(377),
                            Name = "Jewelry",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(377)
                        },
                        new
                        {
                            Id = new Guid("ebe643e6-9dae-4c28-b85d-95e5b7737167"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(378),
                            Name = "Merch",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(378)
                        },
                        new
                        {
                            Id = new Guid("a1190251-f42d-4e04-849e-7e8c743ceabf"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(380),
                            Name = "Music",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(381)
                        });
                });

            modelBuilder.Entity("bob_api.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3b8b397e-ac12-4c33-82a9-b830a207a079"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(628),
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(628),
                            UserId = new Guid("3a221282-4db5-491d-a990-0c08df2ee9e7"),
                            status = "Pending"
                        });
                });

            modelBuilder.Entity("bob_api.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WishlistId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WishlistId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("345175da-d1be-48b4-93e5-bd559957eeca"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(389),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://github.com/moph13121/bob-k-pop-server/blob/main/images/Jewelry_boys/-az04-ateez-leak-earring-removebg-preview.png",
                            Price = 10,
                            Stock = 10,
                            Title = "Ateez Leak Earring",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(389)
                        },
                        new
                        {
                            Id = new Guid("1d7d0e0a-a2fa-460d-b15f-9d9d92fe4b83"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(393),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://github.com/moph13121/bob-k-pop-server/blob/main/images/Jewelry_boys/-az05-ateez-range-piercing-earring-earcuff-removebg-preview.png",
                            Price = 10,
                            Stock = 10,
                            Title = "Ateez Earcuff",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(393)
                        },
                        new
                        {
                            Id = new Guid("2720e32e-96e3-446c-a331-9b2bfe75d9b6"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(395),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://github.com/moph13121/bob-k-pop-server/blob/main/images/Jewelry_boys/-bs110-bts-nesto-ring-removebg-preview.png",
                            Price = 15,
                            Stock = 10,
                            Title = "BTS Nesto Ring",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(395)
                        },
                        new
                        {
                            Id = new Guid("0068505e-4925-4b61-9cdc-4173e8946e9e"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(396),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://github.com/moph13121/bob-k-pop-server/blob/main/images/Jewelry_boys/-bs114-bts-mao-earring-ear-cuff-piercing-removebg-preview.png",
                            Price = 11,
                            Stock = 10,
                            Title = "BTS Mao Earring",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(397)
                        },
                        new
                        {
                            Id = new Guid("716ba239-89ce-470d-ba4e-a455171d98f0"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(398),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://github.com/moph13121/bob-k-pop-server/blob/main/images/Jewelry_boys/-ex234-exo-transformer-ring-removebg-preview.png",
                            Price = 11,
                            Stock = 10,
                            Title = "Exo Transformer Ring",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(398)
                        },
                        new
                        {
                            Id = new Guid("347390ce-54f8-416b-8c91-8872f42f0623"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(400),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://github.com/moph13121/bob-k-pop-server/blob/main/images/Jewelry_boys/-ex236-exo-new-emblem-necklace-removebg-preview.png",
                            Price = 11,
                            Stock = 10,
                            Title = "Exo Emblem Necklace",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(400)
                        },
                        new
                        {
                            Id = new Guid("5524939f-695e-4de0-8c11-e0a31dbdd126"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(401),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://github.com/moph13121/bob-k-pop-server/blob/main/images/Jewelry_girls/Blackpink_Lisa_necklace-removebg-preview.png",
                            Price = 10,
                            Stock = 10,
                            Title = "BlackPink Lisa Necklace",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(402)
                        },
                        new
                        {
                            Id = new Guid("a4109235-5ca1-41e2-b536-dc38cb73816e"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(405),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://github.com/moph13121/bob-k-pop-server/blob/main/images/Jewelry_girls/blackpink_Lisa_braclet-removebg-preview.png",
                            Price = 10,
                            Stock = 10,
                            Title = "BlackPink Lisa Bracelet",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(405)
                        },
                        new
                        {
                            Id = new Guid("ee123577-64d1-45c6-bf8f-6142f059c928"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(406),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://github.com/moph13121/bob-k-pop-server/blob/main/images/Jewelry_girls/-sn10-girls-generation-smile-earring-piercing-removebg-preview.png",
                            Price = 10,
                            Stock = 10,
                            Title = "Girls Generation Smile Earring",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(406)
                        },
                        new
                        {
                            Id = new Guid("f6e6bb73-bd82-4c07-99f6-1fbc278e8263"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(408),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://github.com/moph13121/bob-k-pop-server/blob/main/images/Jewelry_girls/-sn13-girls-generation-cubic-ribbon-earrings-removebg-preview.png",
                            Price = 10,
                            Stock = 10,
                            Title = "Girls Generation Ribbon Earring",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(408)
                        },
                        new
                        {
                            Id = new Guid("22b43960-2b8d-4d5e-a20c-0817cf26ceae"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(409),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://github.com/moph13121/bob-k-pop-server/blob/main/images/KpopMusic_boys/ATEEZ%20-%20THE%20WORLD%20EP%202%20%20OUTLAW.png",
                            Price = 10,
                            Stock = 10,
                            Title = "Ateez - The World EP 2 OUTLAW",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(410)
                        },
                        new
                        {
                            Id = new Guid("d8168f2f-1fd2-4a42-9966-96dd0212108b"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(412),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://github.com/moph13121/bob-k-pop-server/blob/main/images/KpopMusic_boys/BTS%20JHOPE%20ALBUM%20-%20JACK%20IN%20THE%20BOX.png",
                            Price = 10,
                            Stock = 10,
                            Title = "JHope - JACK IN THE BOX",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(412)
                        },
                        new
                        {
                            Id = new Guid("e6a11740-db8b-4f1f-bd6c-328af93aae04"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(414),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://github.com/moph13121/bob-k-pop-server/blob/main/images/KpopMusic_boys/Stray%20Kids%20-%20MAXIDENT.png",
                            Price = 10,
                            Stock = 10,
                            Title = "Stray Kids - MAXIDENT",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(414)
                        },
                        new
                        {
                            Id = new Guid("4bd80771-b963-40de-91c4-6306fe54e26c"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(415),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://github.com/moph13121/bob-k-pop-server/blob/main/images/KpopMusic_boys/SEVENTEEN%20-%20FML%2010th%20Mini%20Album.png",
                            Price = 10,
                            Stock = 10,
                            Title = "SEVENTEEN - FML 10th Mini Album",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(415)
                        },
                        new
                        {
                            Id = new Guid("7adf4645-d242-4cd5-9348-1d0249817e82"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(417),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://github.com/moph13121/bob-k-pop-server/blob/main/images/KpopMusic_girls/(G)I-DLE%20-%20I%20FEEL%206th%20Mini%20Album.png",
                            Price = 10,
                            Stock = 10,
                            Title = "(G)I-DLE - I FEEL 6th Mini Album",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(417)
                        },
                        new
                        {
                            Id = new Guid("d559032c-dc8b-4998-bf91-4c70c8bb67b4"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(460),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://github.com/moph13121/bob-k-pop-server/blob/main/images/KpopMusic_girls/RED_VELVET%20ALBUM.png",
                            Price = 10,
                            Stock = 10,
                            Title = "Red Velvet - Album",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(460)
                        },
                        new
                        {
                            Id = new Guid("bd6db80f-3fe0-4bcc-82c4-b936a3cfe519"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(462),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://github.com/moph13121/bob-k-pop-server/blob/main/images/KpopMusic_girls/LE%20SSERAFIM%20ALBUM-%20ANTIFRAGILE.png",
                            Price = 10,
                            Stock = 10,
                            Title = "LE SSERAFIM - ANTIFRAGILE",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(462)
                        },
                        new
                        {
                            Id = new Guid("dc5c2184-4b59-4961-a245-bf15f16aa871"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(464),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://github.com/moph13121/bob-k-pop-server/blob/main/images/KpopMusic_girls/BLACKPINK%20LISA%20ALBUM%20-%20LALISA.png",
                            Price = 10,
                            Stock = 10,
                            Title = "BlackPink Lisa - LALISA",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(464)
                        },
                        new
                        {
                            Id = new Guid("9dc7ce12-5b6d-41c2-991b-adaeb9757abc"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(466),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://github.com/moph13121/bob-k-pop-server/blob/main/images/KpopMusic_girls/TWICE%20ALBUM%20-%20WITH%20YOU-TH.jpg",
                            Price = 10,
                            Stock = 10,
                            Title = "Twice - With You",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(466)
                        },
                        new
                        {
                            Id = new Guid("a44475aa-636c-45b1-b018-426d5d5d3a59"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(467),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://github.com/moph13121/bob-k-pop-server/blob/main/images/Lightsticks_boys/BTS%20Official%20Light%20Stick%20Special%20Edition.png",
                            Price = 10,
                            Stock = 10,
                            Title = "BTS Official Light Stick Special Edition",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(468)
                        },
                        new
                        {
                            Id = new Guid("1328f1e4-0b59-4fe0-847a-3a151e5bdcfb"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(469),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://github.com/moph13121/bob-k-pop-server/blob/main/images/Lightsticks_boys/BIGBANG%20OFFICIAL%20LIGHT%20STICK%20VER%204.png",
                            Price = 10,
                            Stock = 10,
                            Title = "BigBang Official Light Stick ",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(469)
                        },
                        new
                        {
                            Id = new Guid("faa81faf-2da6-4432-91dc-e7ff40804916"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(471),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://github.com/moph13121/bob-k-pop-server/blob/main/images/Lightsticks_boys/ATEEZ%20OFFICIAL%20LIGHTSTICK%20VER%202%20.png",
                            Price = 10,
                            Stock = 10,
                            Title = "Ateez Official Light Ver.2",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(471)
                        },
                        new
                        {
                            Id = new Guid("855b187b-90e0-440b-af95-f201d7abf426"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(472),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://github.com/moph13121/bob-k-pop-server/blob/main/images/Lightsticks_girls/BLACKPINK%20OFFICIAL%20LIGHTSTICK%20VER%202%20%E2%80%93%20NEW%20MODEL.png",
                            Price = 10,
                            Stock = 10,
                            Title = "Blackpink Official Lightstick Ver.2",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(473)
                        },
                        new
                        {
                            Id = new Guid("b599059f-1fef-435b-8e4b-b186f58f8530"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(475),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://github.com/moph13121/bob-k-pop-server/blob/main/images/Lightsticks_girls/GIDLE%20OFFICIAL%20LIGHTSTICK%20VER..png",
                            Price = 10,
                            Stock = 10,
                            Title = "(G)I-DLE.",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(476)
                        },
                        new
                        {
                            Id = new Guid("a9a6354a-b307-4e2f-a3ff-08ac4e774dd4"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(477),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://github.com/moph13121/bob-k-pop-server/blob/main/images/Lightsticks_girls/LE%20SSERAFIM%20OFFICIAL%20LIGHTSTICK.png",
                            Price = 10,
                            Stock = 10,
                            Title = "LE SSERAFIM Official Lightstick",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(477)
                        },
                        new
                        {
                            Id = new Guid("ad6db8dc-79e3-494d-9c3e-3a57418ddbe9"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(479),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://github.com/moph13121/bob-k-pop-server/blob/main/images/Lightsticks_girls/RED%20VELVET%20OFFICIAL%20LIGHTSTICK.png",
                            Price = 10,
                            Stock = 10,
                            Title = "Red Velvet Official Lightstick",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(479)
                        },
                        new
                        {
                            Id = new Guid("5497fb11-da6a-4ba2-b09f-0cff76b57c78"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(480),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://github.com/moph13121/bob-k-pop-server/blob/main/images/Lightsticks_girls/GIRLS_GENERATION_OFFICIAL_LIGHTSTICK.png",
                            Price = 10,
                            Stock = 10,
                            Title = "Girls Generation Official Lightstick",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(480)
                        });
                });

            modelBuilder.Entity("bob_api.Models.ProductCategory", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategory");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("345175da-d1be-48b4-93e5-bd559957eeca"),
                            CategoryId = new Guid("713af980-25c7-4527-b563-d20941644593")
                        },
                        new
                        {
                            ProductId = new Guid("345175da-d1be-48b4-93e5-bd559957eeca"),
                            CategoryId = new Guid("082c44a8-5d8c-4b7d-b4aa-ef31cc202338")
                        },
                        new
                        {
                            ProductId = new Guid("345175da-d1be-48b4-93e5-bd559957eeca"),
                            CategoryId = new Guid("651ec71d-6595-4da6-9208-9ee50c3db5d3")
                        },
                        new
                        {
                            ProductId = new Guid("1d7d0e0a-a2fa-460d-b15f-9d9d92fe4b83"),
                            CategoryId = new Guid("713af980-25c7-4527-b563-d20941644593")
                        },
                        new
                        {
                            ProductId = new Guid("1d7d0e0a-a2fa-460d-b15f-9d9d92fe4b83"),
                            CategoryId = new Guid("082c44a8-5d8c-4b7d-b4aa-ef31cc202338")
                        },
                        new
                        {
                            ProductId = new Guid("1d7d0e0a-a2fa-460d-b15f-9d9d92fe4b83"),
                            CategoryId = new Guid("651ec71d-6595-4da6-9208-9ee50c3db5d3")
                        },
                        new
                        {
                            ProductId = new Guid("2720e32e-96e3-446c-a331-9b2bfe75d9b6"),
                            CategoryId = new Guid("713af980-25c7-4527-b563-d20941644593")
                        },
                        new
                        {
                            ProductId = new Guid("2720e32e-96e3-446c-a331-9b2bfe75d9b6"),
                            CategoryId = new Guid("082c44a8-5d8c-4b7d-b4aa-ef31cc202338")
                        },
                        new
                        {
                            ProductId = new Guid("2720e32e-96e3-446c-a331-9b2bfe75d9b6"),
                            CategoryId = new Guid("79ffc79c-1203-45d7-a60d-522116a07589")
                        },
                        new
                        {
                            ProductId = new Guid("0068505e-4925-4b61-9cdc-4173e8946e9e"),
                            CategoryId = new Guid("713af980-25c7-4527-b563-d20941644593")
                        },
                        new
                        {
                            ProductId = new Guid("0068505e-4925-4b61-9cdc-4173e8946e9e"),
                            CategoryId = new Guid("082c44a8-5d8c-4b7d-b4aa-ef31cc202338")
                        },
                        new
                        {
                            ProductId = new Guid("0068505e-4925-4b61-9cdc-4173e8946e9e"),
                            CategoryId = new Guid("79ffc79c-1203-45d7-a60d-522116a07589")
                        },
                        new
                        {
                            ProductId = new Guid("5524939f-695e-4de0-8c11-e0a31dbdd126"),
                            CategoryId = new Guid("713af980-25c7-4527-b563-d20941644593")
                        },
                        new
                        {
                            ProductId = new Guid("5524939f-695e-4de0-8c11-e0a31dbdd126"),
                            CategoryId = new Guid("c468a87b-5cbc-4d7a-bce1-ac38424a6b1b")
                        },
                        new
                        {
                            ProductId = new Guid("5524939f-695e-4de0-8c11-e0a31dbdd126"),
                            CategoryId = new Guid("35db38c3-8949-4c43-bf66-2379c5f40d12")
                        },
                        new
                        {
                            ProductId = new Guid("a4109235-5ca1-41e2-b536-dc38cb73816e"),
                            CategoryId = new Guid("713af980-25c7-4527-b563-d20941644593")
                        },
                        new
                        {
                            ProductId = new Guid("a4109235-5ca1-41e2-b536-dc38cb73816e"),
                            CategoryId = new Guid("c468a87b-5cbc-4d7a-bce1-ac38424a6b1b")
                        },
                        new
                        {
                            ProductId = new Guid("a4109235-5ca1-41e2-b536-dc38cb73816e"),
                            CategoryId = new Guid("35db38c3-8949-4c43-bf66-2379c5f40d12")
                        },
                        new
                        {
                            ProductId = new Guid("ee123577-64d1-45c6-bf8f-6142f059c928"),
                            CategoryId = new Guid("713af980-25c7-4527-b563-d20941644593")
                        },
                        new
                        {
                            ProductId = new Guid("ee123577-64d1-45c6-bf8f-6142f059c928"),
                            CategoryId = new Guid("c468a87b-5cbc-4d7a-bce1-ac38424a6b1b")
                        },
                        new
                        {
                            ProductId = new Guid("ee123577-64d1-45c6-bf8f-6142f059c928"),
                            CategoryId = new Guid("783a12af-a925-456a-82b1-8a6d999998dc")
                        },
                        new
                        {
                            ProductId = new Guid("f6e6bb73-bd82-4c07-99f6-1fbc278e8263"),
                            CategoryId = new Guid("713af980-25c7-4527-b563-d20941644593")
                        },
                        new
                        {
                            ProductId = new Guid("f6e6bb73-bd82-4c07-99f6-1fbc278e8263"),
                            CategoryId = new Guid("c468a87b-5cbc-4d7a-bce1-ac38424a6b1b")
                        },
                        new
                        {
                            ProductId = new Guid("f6e6bb73-bd82-4c07-99f6-1fbc278e8263"),
                            CategoryId = new Guid("783a12af-a925-456a-82b1-8a6d999998dc")
                        },
                        new
                        {
                            ProductId = new Guid("716ba239-89ce-470d-ba4e-a455171d98f0"),
                            CategoryId = new Guid("713af980-25c7-4527-b563-d20941644593")
                        },
                        new
                        {
                            ProductId = new Guid("716ba239-89ce-470d-ba4e-a455171d98f0"),
                            CategoryId = new Guid("082c44a8-5d8c-4b7d-b4aa-ef31cc202338")
                        },
                        new
                        {
                            ProductId = new Guid("716ba239-89ce-470d-ba4e-a455171d98f0"),
                            CategoryId = new Guid("f4ccb7fe-4090-4e30-8ade-1a3be7c8c266")
                        },
                        new
                        {
                            ProductId = new Guid("347390ce-54f8-416b-8c91-8872f42f0623"),
                            CategoryId = new Guid("713af980-25c7-4527-b563-d20941644593")
                        },
                        new
                        {
                            ProductId = new Guid("347390ce-54f8-416b-8c91-8872f42f0623"),
                            CategoryId = new Guid("082c44a8-5d8c-4b7d-b4aa-ef31cc202338")
                        },
                        new
                        {
                            ProductId = new Guid("347390ce-54f8-416b-8c91-8872f42f0623"),
                            CategoryId = new Guid("f4ccb7fe-4090-4e30-8ade-1a3be7c8c266")
                        },
                        new
                        {
                            ProductId = new Guid("22b43960-2b8d-4d5e-a20c-0817cf26ceae"),
                            CategoryId = new Guid("a1190251-f42d-4e04-849e-7e8c743ceabf")
                        },
                        new
                        {
                            ProductId = new Guid("22b43960-2b8d-4d5e-a20c-0817cf26ceae"),
                            CategoryId = new Guid("082c44a8-5d8c-4b7d-b4aa-ef31cc202338")
                        },
                        new
                        {
                            ProductId = new Guid("22b43960-2b8d-4d5e-a20c-0817cf26ceae"),
                            CategoryId = new Guid("651ec71d-6595-4da6-9208-9ee50c3db5d3")
                        },
                        new
                        {
                            ProductId = new Guid("d8168f2f-1fd2-4a42-9966-96dd0212108b"),
                            CategoryId = new Guid("a1190251-f42d-4e04-849e-7e8c743ceabf")
                        },
                        new
                        {
                            ProductId = new Guid("d8168f2f-1fd2-4a42-9966-96dd0212108b"),
                            CategoryId = new Guid("082c44a8-5d8c-4b7d-b4aa-ef31cc202338")
                        },
                        new
                        {
                            ProductId = new Guid("d8168f2f-1fd2-4a42-9966-96dd0212108b"),
                            CategoryId = new Guid("79ffc79c-1203-45d7-a60d-522116a07589")
                        },
                        new
                        {
                            ProductId = new Guid("e6a11740-db8b-4f1f-bd6c-328af93aae04"),
                            CategoryId = new Guid("a1190251-f42d-4e04-849e-7e8c743ceabf")
                        },
                        new
                        {
                            ProductId = new Guid("e6a11740-db8b-4f1f-bd6c-328af93aae04"),
                            CategoryId = new Guid("082c44a8-5d8c-4b7d-b4aa-ef31cc202338")
                        },
                        new
                        {
                            ProductId = new Guid("e6a11740-db8b-4f1f-bd6c-328af93aae04"),
                            CategoryId = new Guid("8d7b666b-d420-49fc-921e-507fb60f0c56")
                        },
                        new
                        {
                            ProductId = new Guid("4bd80771-b963-40de-91c4-6306fe54e26c"),
                            CategoryId = new Guid("7fc4d300-3c0a-4a94-ac2d-2c1572270799")
                        },
                        new
                        {
                            ProductId = new Guid("4bd80771-b963-40de-91c4-6306fe54e26c"),
                            CategoryId = new Guid("a1190251-f42d-4e04-849e-7e8c743ceabf")
                        },
                        new
                        {
                            ProductId = new Guid("4bd80771-b963-40de-91c4-6306fe54e26c"),
                            CategoryId = new Guid("082c44a8-5d8c-4b7d-b4aa-ef31cc202338")
                        },
                        new
                        {
                            ProductId = new Guid("7adf4645-d242-4cd5-9348-1d0249817e82"),
                            CategoryId = new Guid("a1190251-f42d-4e04-849e-7e8c743ceabf")
                        },
                        new
                        {
                            ProductId = new Guid("7adf4645-d242-4cd5-9348-1d0249817e82"),
                            CategoryId = new Guid("c2999434-3a40-4773-9874-3480b407b468")
                        },
                        new
                        {
                            ProductId = new Guid("7adf4645-d242-4cd5-9348-1d0249817e82"),
                            CategoryId = new Guid("c468a87b-5cbc-4d7a-bce1-ac38424a6b1b")
                        },
                        new
                        {
                            ProductId = new Guid("d559032c-dc8b-4998-bf91-4c70c8bb67b4"),
                            CategoryId = new Guid("c468a87b-5cbc-4d7a-bce1-ac38424a6b1b")
                        },
                        new
                        {
                            ProductId = new Guid("d559032c-dc8b-4998-bf91-4c70c8bb67b4"),
                            CategoryId = new Guid("a1190251-f42d-4e04-849e-7e8c743ceabf")
                        },
                        new
                        {
                            ProductId = new Guid("d559032c-dc8b-4998-bf91-4c70c8bb67b4"),
                            CategoryId = new Guid("71b337d1-044b-4e1d-a006-c1ac44b390fd")
                        },
                        new
                        {
                            ProductId = new Guid("bd6db80f-3fe0-4bcc-82c4-b936a3cfe519"),
                            CategoryId = new Guid("c468a87b-5cbc-4d7a-bce1-ac38424a6b1b")
                        },
                        new
                        {
                            ProductId = new Guid("bd6db80f-3fe0-4bcc-82c4-b936a3cfe519"),
                            CategoryId = new Guid("a1190251-f42d-4e04-849e-7e8c743ceabf")
                        },
                        new
                        {
                            ProductId = new Guid("bd6db80f-3fe0-4bcc-82c4-b936a3cfe519"),
                            CategoryId = new Guid("fb06df6e-5c03-40a0-a393-36046864dd38")
                        },
                        new
                        {
                            ProductId = new Guid("dc5c2184-4b59-4961-a245-bf15f16aa871"),
                            CategoryId = new Guid("c468a87b-5cbc-4d7a-bce1-ac38424a6b1b")
                        },
                        new
                        {
                            ProductId = new Guid("dc5c2184-4b59-4961-a245-bf15f16aa871"),
                            CategoryId = new Guid("a1190251-f42d-4e04-849e-7e8c743ceabf")
                        },
                        new
                        {
                            ProductId = new Guid("dc5c2184-4b59-4961-a245-bf15f16aa871"),
                            CategoryId = new Guid("35db38c3-8949-4c43-bf66-2379c5f40d12")
                        },
                        new
                        {
                            ProductId = new Guid("9dc7ce12-5b6d-41c2-991b-adaeb9757abc"),
                            CategoryId = new Guid("c468a87b-5cbc-4d7a-bce1-ac38424a6b1b")
                        },
                        new
                        {
                            ProductId = new Guid("9dc7ce12-5b6d-41c2-991b-adaeb9757abc"),
                            CategoryId = new Guid("a1190251-f42d-4e04-849e-7e8c743ceabf")
                        },
                        new
                        {
                            ProductId = new Guid("9dc7ce12-5b6d-41c2-991b-adaeb9757abc"),
                            CategoryId = new Guid("b064dda5-3ae4-43f4-a265-604ee6b8bda6")
                        },
                        new
                        {
                            ProductId = new Guid("a44475aa-636c-45b1-b018-426d5d5d3a59"),
                            CategoryId = new Guid("082c44a8-5d8c-4b7d-b4aa-ef31cc202338")
                        },
                        new
                        {
                            ProductId = new Guid("a44475aa-636c-45b1-b018-426d5d5d3a59"),
                            CategoryId = new Guid("cb2b831f-9fd1-43d8-867b-f03067414658")
                        },
                        new
                        {
                            ProductId = new Guid("a44475aa-636c-45b1-b018-426d5d5d3a59"),
                            CategoryId = new Guid("79ffc79c-1203-45d7-a60d-522116a07589")
                        },
                        new
                        {
                            ProductId = new Guid("1328f1e4-0b59-4fe0-847a-3a151e5bdcfb"),
                            CategoryId = new Guid("082c44a8-5d8c-4b7d-b4aa-ef31cc202338")
                        },
                        new
                        {
                            ProductId = new Guid("1328f1e4-0b59-4fe0-847a-3a151e5bdcfb"),
                            CategoryId = new Guid("cb2b831f-9fd1-43d8-867b-f03067414658")
                        },
                        new
                        {
                            ProductId = new Guid("1328f1e4-0b59-4fe0-847a-3a151e5bdcfb"),
                            CategoryId = new Guid("c0a87bf6-0057-48c8-a0a3-5a1548e7e827")
                        },
                        new
                        {
                            ProductId = new Guid("faa81faf-2da6-4432-91dc-e7ff40804916"),
                            CategoryId = new Guid("082c44a8-5d8c-4b7d-b4aa-ef31cc202338")
                        },
                        new
                        {
                            ProductId = new Guid("faa81faf-2da6-4432-91dc-e7ff40804916"),
                            CategoryId = new Guid("cb2b831f-9fd1-43d8-867b-f03067414658")
                        },
                        new
                        {
                            ProductId = new Guid("faa81faf-2da6-4432-91dc-e7ff40804916"),
                            CategoryId = new Guid("651ec71d-6595-4da6-9208-9ee50c3db5d3")
                        },
                        new
                        {
                            ProductId = new Guid("855b187b-90e0-440b-af95-f201d7abf426"),
                            CategoryId = new Guid("c468a87b-5cbc-4d7a-bce1-ac38424a6b1b")
                        },
                        new
                        {
                            ProductId = new Guid("855b187b-90e0-440b-af95-f201d7abf426"),
                            CategoryId = new Guid("cb2b831f-9fd1-43d8-867b-f03067414658")
                        },
                        new
                        {
                            ProductId = new Guid("855b187b-90e0-440b-af95-f201d7abf426"),
                            CategoryId = new Guid("35db38c3-8949-4c43-bf66-2379c5f40d12")
                        },
                        new
                        {
                            ProductId = new Guid("b599059f-1fef-435b-8e4b-b186f58f8530"),
                            CategoryId = new Guid("c468a87b-5cbc-4d7a-bce1-ac38424a6b1b")
                        },
                        new
                        {
                            ProductId = new Guid("b599059f-1fef-435b-8e4b-b186f58f8530"),
                            CategoryId = new Guid("cb2b831f-9fd1-43d8-867b-f03067414658")
                        },
                        new
                        {
                            ProductId = new Guid("b599059f-1fef-435b-8e4b-b186f58f8530"),
                            CategoryId = new Guid("c2999434-3a40-4773-9874-3480b407b468")
                        },
                        new
                        {
                            ProductId = new Guid("a9a6354a-b307-4e2f-a3ff-08ac4e774dd4"),
                            CategoryId = new Guid("c468a87b-5cbc-4d7a-bce1-ac38424a6b1b")
                        },
                        new
                        {
                            ProductId = new Guid("a9a6354a-b307-4e2f-a3ff-08ac4e774dd4"),
                            CategoryId = new Guid("cb2b831f-9fd1-43d8-867b-f03067414658")
                        },
                        new
                        {
                            ProductId = new Guid("a9a6354a-b307-4e2f-a3ff-08ac4e774dd4"),
                            CategoryId = new Guid("fb06df6e-5c03-40a0-a393-36046864dd38")
                        },
                        new
                        {
                            ProductId = new Guid("ad6db8dc-79e3-494d-9c3e-3a57418ddbe9"),
                            CategoryId = new Guid("c468a87b-5cbc-4d7a-bce1-ac38424a6b1b")
                        },
                        new
                        {
                            ProductId = new Guid("ad6db8dc-79e3-494d-9c3e-3a57418ddbe9"),
                            CategoryId = new Guid("cb2b831f-9fd1-43d8-867b-f03067414658")
                        },
                        new
                        {
                            ProductId = new Guid("ad6db8dc-79e3-494d-9c3e-3a57418ddbe9"),
                            CategoryId = new Guid("71b337d1-044b-4e1d-a006-c1ac44b390fd")
                        },
                        new
                        {
                            ProductId = new Guid("5497fb11-da6a-4ba2-b09f-0cff76b57c78"),
                            CategoryId = new Guid("c468a87b-5cbc-4d7a-bce1-ac38424a6b1b")
                        },
                        new
                        {
                            ProductId = new Guid("5497fb11-da6a-4ba2-b09f-0cff76b57c78"),
                            CategoryId = new Guid("cb2b831f-9fd1-43d8-867b-f03067414658")
                        },
                        new
                        {
                            ProductId = new Guid("5497fb11-da6a-4ba2-b09f-0cff76b57c78"),
                            CategoryId = new Guid("783a12af-a925-456a-82b1-8a6d999998dc")
                        });
                });

            modelBuilder.Entity("bob_api.Models.ProductsOrder", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductOrders");
                });

            modelBuilder.Entity("bob_api.Models.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("RatingValue")
                        .HasColumnType("integer")
                        .HasColumnName("rating_value");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("review");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8cb0166d-61a5-463e-b51f-3d35bca7df6f"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(633),
                            ProductId = new Guid("716ba239-89ce-470d-ba4e-a455171d98f0"),
                            RatingValue = 2,
                            Review = "This product was straight garbage cuh",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(633),
                            UserId = new Guid("3a221282-4db5-491d-a990-0c08df2ee9e7")
                        },
                        new
                        {
                            Id = new Guid("251b15e5-9976-4f45-be29-b4ddde1e13a4"),
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(637),
                            ProductId = new Guid("347390ce-54f8-416b-8c91-8872f42f0623"),
                            RatingValue = 5,
                            Review = "This product was straight fire blud",
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(637),
                            UserId = new Guid("3a221282-4db5-491d-a990-0c08df2ee9e7")
                        });
                });

            modelBuilder.Entity("bob_api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3a221282-4db5-491d-a990-0c08df2ee9e7"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "334cd930-a05d-4cc0-9478-fdc0a55a4bfb",
                            CreatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(583),
                            Email = "test@test.no",
                            EmailConfirmed = false,
                            FirstName = "Test",
                            LastName = "Test",
                            LockoutEnabled = false,
                            Password = "password",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e80350ea-5cc9-40b8-ac45-1e863a3ef89f",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2024, 3, 21, 9, 52, 6, 312, DateTimeKind.Utc).AddTicks(584)
                        });
                });

            modelBuilder.Entity("bob_api.Models.Wishlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Wishlist");
                });

            modelBuilder.Entity("bob_api.Models.Order", b =>
                {
                    b.HasOne("bob_api.Models.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("bob_api.Models.Product", b =>
                {
                    b.HasOne("bob_api.Models.Wishlist", null)
                        .WithMany("Products")
                        .HasForeignKey("WishlistId");
                });

            modelBuilder.Entity("bob_api.Models.ProductCategory", b =>
                {
                    b.HasOne("bob_api.Models.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bob_api.Models.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("bob_api.Models.ProductsOrder", b =>
                {
                    b.HasOne("bob_api.Models.Order", "Order")
                        .WithMany("ProductOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bob_api.Models.Product", "Product")
                        .WithMany("ProductsOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("bob_api.Models.Wishlist", b =>
                {
                    b.HasOne("bob_api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("bob_api.Models.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("bob_api.Models.Order", b =>
                {
                    b.Navigation("ProductOrders");
                });

            modelBuilder.Entity("bob_api.Models.Product", b =>
                {
                    b.Navigation("ProductCategories");

                    b.Navigation("ProductsOrders");
                });

            modelBuilder.Entity("bob_api.Models.User", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("bob_api.Models.Wishlist", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
